# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "86aa2065cc8329d2caea22b686784433"
application_url = "https://interests-bruce-famous-create.trycloudflare.com"
embedded = true
name = "new-inboxapp"
handle = "new-inboxapp-65"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_product_listings,write_customers,write_discounts,write_gift_cards,write_order_edits,write_orders,write_products"

[auth]
redirect_urls = [
  "https://interests-bruce-famous-create.trycloudflare.com/auth/callback",
  "https://interests-bruce-famous-create.trycloudflare.com/auth/shopify/callback",
  "https://interests-bruce-famous-create.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
