# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8da0d35c5c37925e97f9f04d87c694f7"
application_url = "https://messaging-compiled-observed-para.trycloudflare.com"
embedded = true
name = "new-inboxapp"
handle = "new-inboxapp-63"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_product_listings,write_customers,write_discounts,write_gift_cards,write_order_edits,write_orders,write_products"

[auth]
redirect_urls = [
  "https://messaging-compiled-observed-para.trycloudflare.com/auth/callback",
  "https://messaging-compiled-observed-para.trycloudflare.com/auth/shopify/callback",
  "https://messaging-compiled-observed-para.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
