# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff60387e845f105323d918fe8be3c606"
application_url = "https://colours-hebrew-utilize-gibraltar.trycloudflare.com"
embedded = true
name = "new-inboxapp"
handle = "new-inboxapp"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://colours-hebrew-utilize-gibraltar.trycloudflare.com/auth/callback",
  "https://colours-hebrew-utilize-gibraltar.trycloudflare.com/auth/shopify/callback",
  "https://colours-hebrew-utilize-gibraltar.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
